### ISSUE TITLE
create a version reponse

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/IoT-STH#16]
It is useful a GET request, ex: **/version**
 and the response could be:
{
  "version": "x.y.z",
  "git_hash": "hash",
  "compile_date": "date_time"
  .... etc. 
}

**Comment by iariasleon** [comment]
Also is useful append a line in log with a version and hash when start the app

**Comment by gtorodelvalle** [comment]
Hi @iariasleon ! If you are OK with the solution provided in https://github.com/telefonicaid/IoT-STH/pull/76 :) Would you be OK with closing this issue? :p

**Comment by iariasleon** [comment]
LGTM
```
{
version: "0.1.0-SNAPSHOT"
}
```

**Comment by iariasleon** [comment]
in log:
```
time=2015-05-22T13:01:09.552Z | lvl=INFO | corr=NA | trans=NA | op=OPER_STH_SERVER_START | msg=Starting up STH server version 0.1.0-SNAPSHOT...

```
