### ISSUE TITLE
Include a configurable maximum size for the log files (rotating log file names)

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/IoT-STH#17]
The maximum size of the log files should be configurable. If the maximum size is reached, a new log file should be created with a new name (typically using suffixes to distinguish amongst them).

**Comment by frbattid** [comment]
Add @vgarciag to the project and ask him about this issue ;)

**Comment by gtorodelvalle** [comment]
OK, in fact he was the one asking for it :)

**Comment by gtorodelvalle** [comment]
I have just added @vgarciag to the fiware-data team (https://github.com/orgs/telefonicaid/teams/fiware-data) and consequently as a collaborator to this repository (https://github.com/telefonicaid/IoT-STH/settings/collaboration(https://github.com/telefonicaid/IoT-STH/settings/collaboration) ;)

**Comment by frbattid** [comment]
Jejeje, I proposed to add @vgarciag because he is the one that implemented the log rotation feature of Cygnus.

**Comment by gtorodelvalle** [comment]
Fixed in https://github.com/telefonicaid/IoT-STH/pull/40 ;) Thanks!
