### ISSUE TITLE
Direct Orion Context Broker to STH notifications (minimalist option)

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/IoT-STH#18]
Although the formal way to populate the time series database managed by the STH component is using the Cygnus component and the sink which will be developed for it, an alternative (so-called 'minimalist') way to populate this database is required.

This alternative mechanism will consist on the direct subscription by the STH component to an Orion Context Broker to receive notifications when the value of the attributes of interest change. As a consequence of these notifications, the STH will update the STH time series database updating the aggregated data for the concrete attributes.

Since both mechanisms (the formal one using Cygnus and the minimalist one using the STH directly) update the same database, it is the responsibility of the people or software in charge of creating the needed subscriptions to avoid updating the time series database twice. This would happen if both mechanisms are enabled for the same attribute of the same entity.

**Comment by iariasleon** [comment]
Append this comment in the README.md

**Comment by gtorodelvalle** [comment]
Thanks! I just launched https://github.com/telefonicaid/IoT-STH/pull/19 to include it ;)
