### ISSUE TITLE
[STH]  "/" from service path header is kept  in mongo collection name

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/IoT-STH#27]
STR (Steps To Reproduce):
1. For a Fiware-ServicePath header such as "/my_serv_path_0"

OBSERVED:
2. The collections created in MongoDB are named : ```sth_/my_serv_path_0``` and ```sth_/my_serv_path_0.aggr```

EXPECTED:
2. The collections created in MongoDB should be named : ```sth__my_serv_path_0``` and ```sth__my_serv_path_0.aggr``` This is, subsituting "/" by "_".

**Comment by gtorodelvalle** [comment]
Already fixed in https://github.com/telefonicaid/IoT-STH/pull/22 once it lands ;) Would you be so kind to close the issue if you agree, @iariasleon :) Thanks!

**Comment by gtorodelvalle** [comment]
In fact, this is already under discussion and has not been implemented (the final decision) yet ;)

**Comment by iariasleon** [comment]
LGTM
In STH is allowed this character
