### ISSUE TITLE
Logging format should adhere to FIWARE guidelines

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/IoT-STH#3]
The logging format of the STH REST API implementation must adhere to the FIWARE format which is basically the following:

time=\<TIMESTAMP\> | lvl=\<LEVEL\> | corr=\<UNICA_CORRELATOR\> | trans=\<TRANSACTION_ID\> | op=\<OPERATION_TYPE\> | msg=\<MESSAGE\>

where:
* TIMESTAMP should be formatted in IEEE RFC 3339 format
* LEVEL is the level of the log (INFO, WARN, ERROR, FATAL, DEBUG or TRACE)
* UNICA_CORRELATOR is the value of the Unica-Correlator HTTP header
* TRANSACTION_ID is an unique id to identify the ongoing transaction
* OPERATION_TYPE is an id referred to the ongoing operation
* MESSAGE typically contains some descriptive information about the event being logged

**Comment by gtorodelvalle** [comment]
The 'Unica-Correlator' HTTP header is (or can be) passed in the request and must be included in the response headers.

**Comment by frbattid** [comment]
This should be labeled as `techdebt` (create it if not existing) and a level (`must`, `should`, `nicetohave`).

**Comment by gtorodelvalle** [comment]
- Implemented in PR https://github.com/telefonicaid/IoT-STH/pull/9
