### ISSUE TITLE
Refactor the server and database functions into their modules

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/IoT-STH#5]
Right now there are functions in the sth_helpers.js module for server and database operations which should be included into their respective modules:
* stopServer() -> sth_server.js
* closeDBConnection() -> sth_database.js

**Comment by frbattid** [comment]
This should be labeled as `techdebt` (create it if not existing) and a level (`must`, `should`, `nicetohave`).

**Comment by gtorodelvalle** [comment]
I'll close this issue since it was covered in https://github.com/telefonicaid/IoT-STH/pull/2 Thanks!
