### ISSUE TITLE
[STH] in aggregated request in month resolution the offset is incorrect

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/IoT-STH#50]
Example:
A notification with date 2015-05-07, in month resolution the offset should be 5 and at the moment is 4.

**Comment by frbattid** [comment]
AFAIK, this is intentional: https://github.com/telefonicaid/IoT-STH/blob/develop/src/sth_database.js#L575

**Comment by iariasleon** [comment]
changed the issue, because the problem is with month resolution and not  with day resolution, the offset in month can't be 0. The behaviour is similar to day resolution.

**Comment by gtorodelvalle** [comment]
Fixed in https://github.com/telefonicaid/IoT-STH/issues/50

**Comment by gtorodelvalle** [comment]
@iariasleon , would you be so kind to check that this issue is successfully fixed in the develop branch and close it if appropriate, please? ;) Thanks!

**Comment by iariasleon** [comment]
LGTM
