### ISSUE TITLE
[STH] what´s the dateFrom value when only we use dateTo?

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/IoT-STH#53]
As the dates (dateFrom and dateTo) are optional, you may not use `dateFrom`, in this case what is its value? The beginning of time?

**Comment by gtorodelvalle** [comment]
The suggested filtering behaviour to be implemented regarding the ```dateFrom``` and ```dateTo``` is the following when retrieving raw data (behaviour for the aggregated case included in comments): 
```
if (from && to) {
  recvTimeFilter = {
    $lte: to, // sthHelper.getOrigin(to, resolution) in the case of aggregates
    $gte: from // sthHelper.getOrigin(from, resolution) in the case of aggregates
  };
} else if (!from) {
  recvTimeFilter = {
    $lte: to // sthHelper.getOrigin(to, resolution) in the case of aggregates
  };
} else if (!to) {
  recvTimeFilter = {
    $gte: from // sthHelper.getOrigin(from, resolution) in the case of aggregates
  };
}
```
this is:
# If the fromDate and the toDate are passed, they are used to filter the requested data between those dates when retrieving the raw data. If aggregates are requested, the corresponding origin for the passed dates and resolution are calculated and applied.
# If only the fromDate is passed, it is used to filter the requested data from that date on when retrieving the raw data. If aggregates are requested, the corresponding origin for the passed date and resolution is calculated and applied (only available aggregates from that origin on are retrieved).
# If only the toDate is passed, it is used to filter the requested data before that date when retrieving the raw data. If aggregates are requested, the corresponding origin for the passed date and resolution is calculated and applied (available aggregates before the passed date are retrieved).
# If no fromDate or toDate are passed, no date filtering is applied. This may end up retrieving quite an amount of data.

What do you think? Should we make the dateFrom and dateTo query params mandatory? :)

**Comment by gtorodelvalle** [comment]
Mentioning @frbattid and @iariasleon to get feedback from you... :p

**Comment by iariasleon** [comment]
I think is not mandatory both parameters, but is necesary  define the limits when these parameters are missing, ex:
- if only fromDate is passed, assume that toDate is now.
- if only toDate is passed, assume that is from beginning of the time
- if both dates are not passed, the range is from beginning of the time until now

**Comment by gtorodelvalle** [comment]
Perfect, that's the suggested implementation ;) Let's see if @frbattid also agrees and I'll include it in a new PR ;) Thanks @iariasleon !

**Comment by frbattid** [comment]
@iariasleon 's proposal makes sense for me. Go for it!

**Comment by gtorodelvalle** [comment]
Fixed in https://github.com/telefonicaid/IoT-STH/pull/80
