### ISSUE TITLE
Add LICENSE and a ContributionPolicy.txt files

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/IoT-STH#7]
The LICENSE file will depend on the chosen license type.

The ContributionPolicy.txt may be directly copied from https://github.com/telefonicaid/fiware-connectors

**Comment by frbattid** [comment]
Once the license type has been decided, a license header must be added to each source file.

**Comment by Rsilnav** [comment]
Contribution Policy added in Pull Request #49

**Comment by gtorodelvalle** [comment]
Fixed in https://github.com/telefonicaid/IoT-STH/pull/49
